NumPy Random

In [17]:
'''
#1.Write a NumPy program to generate five random numbers from the normal distribution.
'''
import numpy as np
x = np.random.normal(size=5)
print(x)

[-0.70390266  1.03681568  0.9640547   1.03034322 -0.8665461 ]


In [16]:
'''
#2.Write a NumPy program to generate six random integers between 10 and 30.
'''
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[15 10 24 23 26 27]


In [14]:
'''
#3.Write a NumPy program to create a 3x3x3 array with random values.
'''
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.60597026 0.85915611 0.32074855]
  [0.4758747  0.52053305 0.98541266]
  [0.16076319 0.280097   0.72864692]]

 [[0.7572718  0.26815135 0.89020609]
  [0.23073596 0.99725298 0.76258805]
  [0.38048288 0.57918874 0.67381115]]

 [[0.79980369 0.79041318 0.71033265]
  [0.72098013 0.58247582 0.61961404]
  [0.31151544 0.6007221  0.2805731 ]]]


In [13]:
'''
#4.Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.
'''
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.03595106 0.02963732 0.0346901  0.87992167 0.70261223]
 [0.62109548 0.30049082 0.8973774  0.3860045  0.77348433]
 [0.03431331 0.1183619  0.83816304 0.33324428 0.63535587]
 [0.16781842 0.22926883 0.31252692 0.7018931  0.92374662]
 [0.76787071 0.82082673 0.98035305 0.12075857 0.71180435]]
Minimum and Maximum Values:
0.029637315141422205 0.9803530456013979


In [11]:
'''
#5.Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.
'''
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
print(y)

Original array: 
[[0.13336252 0.04323503 0.09290302 0.69033471]
 [0.43226526 0.83246093 0.150625   0.33881738]
 [0.39150844 0.79775127 0.26391483 0.51840056]
 [0.35196689 0.88697237 0.05682728 0.54277377]
 [0.52683154 0.64910057 0.48486885 0.51185435]
 [0.1691336  0.23037134 0.75965093 0.99729626]
 [0.99362945 0.84774167 0.53066181 0.09345218]
 [0.22849869 0.83047631 0.57106414 0.38245225]
 [0.94345711 0.1321829  0.07645258 0.75799177]
 [0.01803426 0.37463966 0.80721755 0.55551648]]
First 5 rows of the above array:
[[0.13336252 0.04323503 0.09290302 0.69033471]
 [0.43226526 0.83246093 0.150625   0.33881738]
 [0.39150844 0.79775127 0.26391483 0.51840056]
 [0.35196689 0.88697237 0.05682728 0.54277377]
 [0.52683154 0.64910057 0.48486885 0.51185435]]


In [ ]:
'''
#6.Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).
'''
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

In [10]:
'''
#7.Write a NumPy program to normalize a 3x3 random matrix.
'''
import numpy as np
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.49261285 0.31884278 0.52866029]
 [0.73316849 0.5258387  0.17598287]
 [0.40233282 0.86646964 0.44010997]]
After normalization:
[[0.45856052 0.20689738 0.51076637]
 [0.80694612 0.50667999 0.        ]
 [0.32781214 1.         0.38252305]]


In [9]:
'''
#8.Write a NumPy program to create a random vector of size 10 and sort it.
'''
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.54544435 0.84966648 0.96655733 0.7045382  0.78008639 0.4804652
 0.3590365  0.39034764 0.78681858 0.86235796]
Sorted array:
[0.3590365  0.39034764 0.4804652  0.54544435 0.7045382  0.78008639
 0.78681858 0.84966648 0.86235796 0.96655733]


In [8]:
'''
#9.Write a NumPy program to find the nearest value from a given value in an array.
'''
import numpy as np
x = np.random.uniform(1, 12, 5)
v = 4
n = x.flat[np.abs(x - v).argmin()]
print(n)

3.282653685311122


In [7]:
'''
#10.Write a NumPy program to check two random arrays are equal or not.
'''
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 1 0 0 0]
Second array:
[0 0 1 0 0 0]
Test above two arrays are equal or not!
False


In [6]:
'''
#11.Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.
'''
import numpy as np
x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.85926554 0.73703334 0.0498422  0.12884231 0.35081801 0.91773323
 0.97249693 0.20045378 0.3660715  0.46257624 0.13842051 0.77442819
 0.28655464 0.85632081 0.46436692]
Maximum value replaced by -1:
[ 0.85926554  0.73703334  0.0498422   0.12884231  0.35081801  0.91773323
 -1.          0.20045378  0.3660715   0.46257624  0.13842051  0.77442819
  0.28655464  0.85632081  0.46436692]


In [5]:
'''
#12.Write a NumPy program to find point by point distances of a random vector with shape (10,2) representing coordinates.
'''
import numpy as np
a= np.random.random((10,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.56544382 1.04518015 0.29025116 0.8211624  0.48597393
  0.644881   0.31793886 1.07550864 0.76226764]
 [0.56544382 0.         0.48554335 0.31771085 0.50248332 0.30840509
  0.33616736 0.30752256 0.51257201 0.34619147]
 [1.04518015 0.48554335 0.         0.77232706 0.70924703 0.73126221
  0.65666499 0.78771175 0.17461612 0.4137292 ]
 [0.29025116 0.31771085 0.77232706 0.         0.7193195  0.40142912
  0.52915171 0.24605882 0.82544863 0.47244551]
 [0.8211624  0.50248332 0.70924703 0.7193195  0.         0.33805425
  0.19020369 0.51471859 0.59542738 0.81784632]
 [0.48597393 0.30840509 0.73126221 0.40142912 0.33805425 0.
  0.15971448 0.17711706 0.69377592 0.65229328]
 [0.644881   0.33616736 0.65666499 0.52915171 0.19020369 0.15971448
  0.         0.33098097 0.58651705 0.67335139]
 [0.31793886 0.30752256 0.78771175 0.24605882 0.51471859 0.17711706
  0.33098097 0.         0.78735217 0.6082765 ]
 [1.07550864 0.51257201 0.17461612 0.82544863 0.59542738 0.69377592
  0.58651705 0.78735

In [4]:
'''
#13.Write a NumPy program to find the most frequent value in an array.
'''
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[5 5 3 7 6 9 9 0 8 7 1 6 4 0 9 6 2 2 7 8 7 3 5 3 7 3 1 8 6 8 2 1 0 4 1 7 5
 8 6 1]
Most frequent value in the above array:
7


In [3]:
'''
#14.Write a NumPy program to convert cartesian coordinates to polar coordinates of a random 10x3 matrix representing cartesian coordinates.
'''
import numpy as np
z= np.random.random((10,3))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.07558146 1.05817222 1.24013869 0.81420451 0.51980916 0.92368848
 1.04620946 0.9962279  0.2766911  1.12082597]
[0.90321729 0.58709719 0.79984396 0.08603365 0.64188142 0.11817661
 0.67400646 0.03917987 0.4318423  1.05608276]


In [2]:
'''
#15.Write a NumPy program to find the closest value (to a given scalar) in an array.
'''
import numpy as np
x = np.arange(100)
print("Original array:")
print(x)
a = np.random.uniform(0,100)
print("Value to compare:")
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
90.2577483863723
90


In [1]:
'''
#16.Write a NumPy program to get the n largest values of an array.
'''
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]
