NumPy Math

In [6]:
'''
#1.Write a NumPy program to add, subtract, multiply, divide arguments element-wise.
Sample elements: 4.0, 1.2
'''
import numpy as np
print("Add:")
print(np.add(1.0, 4.0))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))

Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25


In [5]:
'''
#2.Write a NumPy program to compute logarithm of the sum of exponentiations of the inputs, sum of exponentiations of the inputs in base-2.
'''
import numpy as np
l1 = np.log(1e-50)
l2 = np.log(2.5e-50)
print("Logarithm of the sum of exponentiations:")
print(np.logaddexp(l1, l2))
print("Logarithm of the sum of exponentiations of the inputs in base-2:")
print(np.logaddexp2(l1, l2))

Logarithm of the sum of exponentiations:
-113.87649168120691
Logarithm of the sum of exponentiations of the inputs in base-2:
-113.59955522772194


In [4]:
'''
#3.Write a NumPy program to get true division of the element-wise array inputs.
'''
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
print("Division of the array inputs, element-wise:")
print(np.true_divide(x, 3))

Original array:
[0 1 2 3 4 5 6 7 8 9]
Division of the array inputs, element-wise:
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


In [2]:
'''
#4.Write a NumPy program to get the largest integer smaller or equal to the division of the inputs
'''
import numpy as np
x = [1., 2., 3., 4.]
print("Original array:")
print(x)
print("Largest integer smaller or equal to the division of the inputs:")
print(np.floor_divide(x, 1.5))

Original array:
[1.0, 2.0, 3.0, 4.0]
Largest integer smaller or equal to the division of the inputs:
[0. 1. 2. 2.]


In [3]:
'''
#5.Write a NumPy program to get the powers of an array values element-wise.

Note: First array elements raised to powers from second array.
'''
import numpy as np
x = np.arange(7)
print("Original array")
print(x)
print("First array elements raised to powers from second array, element-wise:")
print(np.power(x, 3))

Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[  0   1   8  27  64 125 216]


In [7]:
'''
#6.Write a NumPy program to get the element-wise remainder of an array of division.
'''
import numpy as np
x = np.arange(7)
print("Original array:")
print(x)
print("Element-wise remainder of division:")
print(np.remainder(x, 5))

Original array:
[0 1 2 3 4 5 6]
Element-wise remainder of division:
[0 1 2 3 4 0 1]


In [8]:
'''
#7.Write a NumPy program to calculate the absolute value element-wise.
'''
import numpy as np
x = np.array([-10.2, 122.2, .20])
print("Original array:")
print(x)
print("Element-wise absolute value:")
print(np.absolute(x))

Original array:
[-10.2 122.2   0.2]
Element-wise absolute value:
[ 10.2 122.2   0.2]


In [9]:
'''
#8.Write a NumPy program to round array elements to the given number of decimals.
'''
import numpy as np
x = np.round([1.45, 1.50, 1.55])
print(x)
x = np.round([0.28, .50, .64], decimals=1)
print(x)
x = np.round([.5, 1.5, 2.5, 3.5, 4.5]) # rounds to nearest even value
print(x)

[1. 2. 2.]
[0.3 0.5 0.6]
[0. 2. 2. 4. 4.]


In [10]:
'''
#9.Write a NumPy program to round elements of the array to the nearest integer.
'''
import numpy as np
x = np.array([-.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.0])
print("Original array:")
print(x)
x = np.rint(x)
print("Round elements of the array to the nearest integer:")
print(x)

Original array:
[-0.7 -1.5 -1.7  0.3  1.5  1.8  2. ]
Round elements of the array to the nearest integer:
[-1. -2. -2.  0.  2.  2.  2.]


In [11]:
'''
#10.Write a NumPy program to get the floor, ceiling and truncated values of the elements of an numpy array.
'''
import numpy as np
x = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])
print("Original array:")
print(x)
print("Floor values of the above array elements:")
print(np.floor(x))
print("Ceil values of the above array elements:")
print(np.ceil(x))
print("Truncated values of the above array elements:")
print(np.trunc(x))

Original array:
[-1.6 -1.5 -0.3  0.1  1.4  1.8  2. ]
Floor values of the above array elements:
[-2. -2. -1.  0.  1.  1.  2.]
Ceil values of the above array elements:
[-1. -1. -0.  1.  2.  2.  2.]
Truncated values of the above array elements:
[-1. -1. -0.  0.  1.  1.  2.]


In [12]:
'''
#11.Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.
'''
import numpy as np
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)

First array:
[[0.65002272 0.9223962  0.82471299]
 [0.54099523 0.42259479 0.98534849]
 [0.20621513 0.43238962 0.0293461 ]
 [0.35185821 0.4429339  0.19590679]
 [0.34320087 0.71638939 0.39073803]]
Second array:
[[0.0948771  0.73960199]
 [0.40324362 0.45775862]
 [0.94626698 0.50791232]]
Dot product of two arrays:
[[1.21402132 1.3218748 ]
 [1.15413945 1.0940382 ]
 [0.22169269 0.36535244]
 [0.39737368 0.56249532]
 [0.69118385 0.78022613]]


In [13]:
'''
#12.Write a NumPy program to multiply a matrix by another matrix of complex numbers and create a new matrix of complex numbers.
'''
import numpy as np
x = np.array([1+2j,3+4j])
print("First array:")
print(x)
y = np.array([5+6j,7+8j])
print("Second array:")
print(y)
z = np.vdot(x, y)
print("Product of above two arrays:")
print(z)

First array:
[1.+2.j 3.+4.j]
Second array:
[5.+6.j 7.+8.j]
Product of above two arrays:
(70-8j)


In [14]:
'''
#13.Write a NumPy program to create an inner product of two arrays.
'''
import numpy as np
x = np.arange(24).reshape((2,3,4))
print("Array x:")
print(x)
print("Array y:")
y = np.arange(4)
print(y)
print("Inner of x and y arrays:")
print(np.inner(x, y))

Array x:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Array y:
[0 1 2 3]
Inner of x and y arrays:
[[ 14  38  62]
 [ 86 110 134]]


In [15]:
'''
#14.Write a NumPy program to generate inner, outer, and cross products of matrices and vectors.
'''
import numpy as np
x = np.array([1, 4, 0], float)
y = np.array([2, 2, 1], float)
print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)
print("Inner product of x and y:")
print(np.inner(x, y))
print("Outer product of x and y:")
print(np.outer(x, y))
print("Cross product of x and y:")
print(np.cross(x, y))

Matrices and vectors.
x:
[1. 4. 0.]
y:
[2. 2. 1.]
Inner product of x and y:
10.0
Outer product of x and y:
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
Cross product of x and y:
[ 4. -1. -6.]


In [16]:
'''
#15.Write a NumPy program to generate a matrix product of two arrays.
'''
import numpy as np
x = [[1, 0], [1, 1]]
y = [[3, 1], [2, 2]]
print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)
print("Matrix product of above two arrays:")
print(np.matmul(x, y))

Matrices and vectors.
x:
[[1, 0], [1, 1]]
y:
[[3, 1], [2, 2]]
Matrix product of above two arrays:
[[3 1]
 [5 3]]


In [17]:
'''
#16.Write a NumPy program to find the roots of the following polynomials.
a) x2 − 4x + 7.
b) x4 − 11x3 + 9x2 + 11x – 10
'''
import numpy as np
print("Roots of the first polynomial:")
print(np.roots([1, -2, 1]))
print("Roots of the second polynomial:")
print(np.roots([1, -12, 10, 7, -10]))

Roots of the first polynomial:
[1. 1.]
Roots of the second polynomial:
[11.04461946+0.j        -0.8711421 +0.j         0.91326132+0.4531004j
  0.91326132-0.4531004j]


In [18]:
'''
#17.Write a NumPy program to compute the following polynomial values.
a) x2 − 4x + 7, when x = 2
b) x4 − 11x3 + 9x2 + 11x – 10, when x = 3
'''
import numpy as np
print("Polynomial value when x = 2:")
print(np.polyval([1, -2, 1], 2))
print("Polynomial value when x = 3:")
print(np.polyval([1, -12, 10, 7, -10], 3))

Polynomial value when x = 2:
1
Polynomial value when x = 3:
-142


In [20]:
'''
#18.Write a NumPy program to add one polynomial to another, subtract one polynomial from another, multiply one polynomial by another and divide one polynomial by another.
'''
from numpy.polynomial import polynomial as P
x = (10,20,30)
y = (30,40,50)
print("Add one polynomial to another:")
print(P.polyadd(x,y))
print("Subtract one polynomial from another:")
print(P.polysub(x,y))
print("Multiply one polynomial by another:")
print(P.polymul(x,y))
print("Divide one polynomial by another:")
print(P.polydiv(x,y))

Add one polynomial to another:
[40. 60. 80.]
Subtract one polynomial from another:
[-20. -20. -20.]
Multiply one polynomial by another:
[ 300. 1000. 2200. 2200. 1500.]
Divide one polynomial by another:
(array([0.6]), array([-8., -4.]))


In [19]:
'''
#19.Write a NumPy program to calculate mean across dimension, in a 2D numpy array.
'''
import numpy as np
x = np.array([[10, 30], [20, 60]])
print("Original array:")
print(x)
print("Mean of each row:")
print(x.mean(axis=0))
print("Mean of each column:")
print(x.mean(axis=1))

Original array:
[[10 30]
 [20 60]]
Mean of each row:
[15. 45.]
Mean of each column:
[20. 40.]


In [21]:
'''
#20.Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements.
'''
import numpy as np
x = np.random.randn(1000)
print("Average of the array elements:")
mean = x.mean()
print(mean)
print("Standard deviation of the array elements:")
std = x.std()
print(std)
print("Variance of the array elements:")
var = x.var()
print(var)

Average of the array elements:
-0.005946023739128627
Standard deviation of the array elements:
1.026304659763013
Variance of the array elements:
1.0533012546512737


In [22]:
'''
#21.Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degrees.
'''
import numpy as np
print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cosine: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tangent: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))


sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
